# ==============================================================================
# Ansible Inventory - Robot Shop Kubernetes Cluster
# ==============================================================================

[masters]
k8s-master-1 ansible_host=192.168.180.101

[workers]
k8s-master-2 ansible_host=192.168.180.102
k8s-master-3 ansible_host=192.168.180.103

# Nhóm chung chứa toàn bộ các node trong cụm K8s
[k8s_cluster:children]
masters
workers

# Cấu hình biến dùng chung cho tất cả các máy
[k8s_cluster:vars]
ansible_user=devops
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
# Cho phép tự động leo quyền root bằng sudo
ansible_become=yes
ansible_become_method=sudo
